<?php

return [

    /*
     * The model that will be used as the model for media.
     */
    'model' => \Spatie\MediaLibrary\MediaCollections\Models\Media::class,

    /*
     * The disk where the media should be stored. The default is the 'public' disk.
     */
    'disk_name' => 'public',

    /*
     * The directory within the disk where the media should be stored. The default is 'media'.
     */
    'directory_name' => 'products',

    /*
     * The url for the disk where the media should be stored. The default is the 'public' disk.
     */
    'url' => env('MEDIA_URL'),

    /*
     * The disk where the media should be stored for conversions. The default is the 'public' disk.
     */
    'conversions_disk' => 'public',

    /*
     * The directory where the media should be stored for conversions.
     */
    'conversions_directory_name' => 'conversions',

    /*
     * The size of images that will be generated by the conversions.
     */
    'image_conversions' => [
        'thumb' => [
            'width' => 300,
            'height' => 300,
            'quality' => 90,
        ],
        'medium' => [
            'width' => 600,
            'height' => 600,
            'quality' => 90,
        ],
    ],

    /*
     * The size of the media files.
     */
    'max_file_size' => 1024 * 24, // 24 MB

    /*
     * The allowed file types.
     */
    'allowed_file_types' => [
        'image/jpeg',
        'image/png',
        'image/gif',
    ],

    /*
     * If you want to enable the default conversion to be applied to each image upload, set it to true.
     */
    'use_default_conversion' => true,
];
